[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/manifest.json"
  to = "/static/manifest.json"
  status = 200

[[headers]]
  for = "/static/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
